### ISSUE TITLE
Naming convention?

### ISSUE THREAD

**Issue by tomexou** [Efferent-Health/HL7-dotnetcore#2]
I noticed that Message object has setValue(), getAck() methods which are public, they should be uppercase of first letter in NET naming convention, ex: SetValue() or GetAck().

Hope this nice library can follow it, otherwise it's so weird in using.
BTW, it's a good library, thanks.

**Comment by jaime-olivares** [comment]
sorry, this is a fork. the names are coming from the original implementation. As there is people already using this library, it is not so simple to do the change.
Will reevaluate in a while.

**Comment by jaime-olivares** [comment]
I have renamed the public methods and added a deprecation warning for the old ones.

**Comment by MovGP0** [comment]
I guess the .NET naming conventions are still not met. The source feels way more like Java and not like C#. Ie. insted of `foo.SetValue(index, value)` you should use `foo[index] = value`. Constants are in `UPPER_CASE` instead of `PascalCase`, Collections don't implement `ICollection`, etc. 

Maybe we should consider a major refactoring?

**Comment by jaime-olivares** [comment]
Hi, this is a fork, not my original source code.

Although I may consider a gradual refactoring in the future, it is not a priority, since users would just get the nuget package.
