### ISSUE TITLE
How can we use it with 4.5 framework?

### ISSUE THREAD

**Issue by navneetgarggate6** [Efferent-Health/HL7-dotnetcore#42]
Is there any way to use it with 4.5?

**Comment by jaime-olivares** [comment]
No, there is not. This is a .Net Core library without any legacy goal. For using it in classic desktop applications, you can use .Net 4.7.1 which is highly compatible with .Net Core libraries.

You can also use .Net Framework since 4.6.1, although there are some complications (read https://github.com/dotnet/standard/issues/514)
