### ISSUE TITLE
How to get the next element value e.g OBR have result value written in next NTE element. 

### ISSUE THREAD

**Issue by Tabraizahmed** [Efferent-Health/HL7-dotnetcore#56]
Hello there. 
First of all I want to thank you about this awesome tool, it really helps me to solve HL7 based problems. 
I am stuck in one scenario Like I have OBR elements like below 

OBR|42|11474-211913|K7084882|5272^**HLA DRB1** HR-DRB3,4,5 INTERMEDIATE RESOLUTION|||202002111020|||||||||1912089277^Hello^world^^^^^^N||||||20200221|||F

And after that there is OBX element 

OBX|1|ST|R166215^DBR1^^^LN||Comment||||||F||||LI5

And after this I have NTE element 

NTE|1||                         DRB1*14:04:01:01

Now the problem is the OBR element have result value in NTE element that is DRB1*14:04:01:01 
So any idea that how I reach to the next NTE element and pick the result value. NTE elements are repeated and coming after every OBR elements. I can't hardcode the index of these elements. 

I really appreciate if you let me know is that possible with this parser. 

Thanks

**Comment by chrismidolo** [comment]
I've solved this before by hand, the issue is that NTE segments in results messages are actually quite complex, they can apply to either the OBR, or the OBX and are not single entities.

The solution I came up with was basically to get the segment segment list and just start accumulating NTE segments until the next OBX appears. 

You could implement this into the library with something like a GetSegmentBetween(string segmentToFind, string parentSegment, int parentSegment index, but it's probably something that would be better off in a separate helper library than build directly into this library.

**Comment by jaime-olivares** [comment]
Hi @Tabraizahmed 
Complementing @chrismidolo response.
The `Segments()` method will return a list of all the segments in the same order as coming in the HL7 message, so you can parse them in the right order by using `GetAllFields()` for each segment object.
So I think you already have enough tools for doing it.
